import os

URL = 'http://localhost:5050'

TEST_SEND_EMAIL_DOMAIN = os.getenv('CAPE_TEST_SEND_EMAIL_DOMAIN', 'REPLACEME')
TEST_RECEIVE_EMAIL_DOMAIN = os.getenv('CAPE_TEST_RECEIVE_EMAIL_DOMAIN', 'REPLACEME')
